import logging
from io import BytesIO
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from models.schemas import PlanResponse

logger = logging.getLogger(__name__)


def generate_itinerary_pdf(plan: "PlanResponse") -> bytes:
    """Generate a PDF itinerary from a PlanResponse object."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate,
            Paragraph,
            Spacer,
            Table,
            TableStyle,
            HRFlowable,
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        raise RuntimeError(
            "reportlab is required for PDF export. Install with: pip install reportlab"
        )

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    # Title style
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        spaceAfter=6,
        textColor=colors.HexColor("#1a1a2e"),
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        spaceAfter=20,
        textColor=colors.HexColor("#666666"),
        alignment=TA_CENTER,
    )
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontSize=14,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor("#0066cc"),
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=4,
        textColor=colors.HexColor("#333333"),
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=3,
        leftIndent=15,
        textColor=colors.HexColor("#444444"),
    )

    # Header
    story.append(Paragraph("GeoAgent Travel Itinerary", title_style))
    story.append(
        Paragraph(
            f"{plan.destination} | {plan.days}-Day Plan | Generated {datetime.now().strftime('%B %d, %Y')}",
            subtitle_style,
        )
    )
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dddddd")))
    story.append(Spacer(1, 12))

    # Weather summary
    if plan.weather_summary:
        story.append(Paragraph("Weather Overview", section_style))
        story.append(Paragraph(plan.weather_summary, body_style))
        story.append(Spacer(1, 8))

    # Safety notes
    if plan.safety_notes:
        story.append(Paragraph("Safety Notes", section_style))
        for note in plan.safety_notes:
            story.append(Paragraph(f"- {note}", bullet_style))
        story.append(Spacer(1, 8))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#eeeeee")))
    story.append(Spacer(1, 8))

    # Daily itinerary
    story.append(Paragraph("Daily Itinerary", section_style))

    for day in plan.itinerary:
        story.append(Paragraph(f"Day {day.day}: {day.theme}", section_style))

        if day.activities:
            story.append(Paragraph("Activities", body_style))
            for act in day.activities:
                story.append(Paragraph(f"  {act}", bullet_style))

        if day.meals:
            story.append(Paragraph("Dining", body_style))
            for meal in day.meals:
                story.append(Paragraph(f"  {meal}", bullet_style))

        if day.tips:
            story.append(Paragraph("Tips", body_style))
            for tip in day.tips:
                story.append(Paragraph(f"  {tip}", bullet_style))

        story.append(Spacer(1, 10))

    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dddddd")))
    story.append(Spacer(1, 6))
    story.append(
        Paragraph(
            "Generated by GeoAgent - AI-Powered Local Tourism Intelligence",
            subtitle_style,
        )
    )

    doc.build(story)
    return buffer.getvalue()
